/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface HealthDataUpdateInput {
  data: {
    age?: number;
    gender?: 'male' | 'female';
    height?: number;
    weight?: number;
  };
  searchBy: {
    id: string;
  };
}
