/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AuthUserCreateInput {
  data: {
    email: string;
    password: string;
  };
}

export interface AuthUserSearchInput {
  searchBy?: {
    email?: string;
    id?: string;
  };
}
