@startuml high-level-diagram-definitions

!startsub FIREBASE_AUTH
node "<<external-service>> \nFirebase Auth" as FirebaseAuth
!endsub

!startsub MOBILE_APPLICATION
component [Mobile Application] as MobileApplication
!endsub

!startsub SPEECH_2_DIET_API
component [Speech2Diet API] as Speech2DietAPI
!endsub

!startsub FIRESTORE_DB
database "<<external-service>> \nFirestore DB" as FirestoreDB
!endsub

!startsub AUDIO_STORAGE
node "<<external-service>> \nAudio Storage" as AudioStorage
!endsub

!startsub RABBIT_MQ
component "RabbitMQ" as RabbitMQ
!endsub

!startsub SPEECH_2_NUTRITION
component "Speech2Nutrition" as Speech2Nutrition
!endsub

!startsub NUTRITION_DB
database "Nutrition DB" as NutritionDB
!endsub

!startsub CHAT_GPT
node "<<external-service>> \nChat GPT" as ChatGPT
!endsub

!startsub WHISPER
node "<<external-service>> \nWhisper" as Whisper
!endsub

@enduml