@startuml speech2nutrition-high-level-diagram
skinparam padding 10
skinparam defaultTextAlignment center

!includesub definitions.puml!SPEECH_2_NUTRITION
!includesub definitions.puml!NUTRITION_DB
!includesub definitions.puml!CHAT_GPT
!includesub definitions.puml!WHISPER

!includesub definitions.puml!AUDIO_STORAGE

Speech2Nutrition --> NutritionDB : query nutrition information
Speech2Nutrition --> ChatGPT : parses text using
Speech2Nutrition --> Whisper : transcribes audios using
Speech2Nutrition --> AudioStorage : reads audio files \n [http]

@enduml