// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	TARGET_URL: string;
	RATELIMIT_SERVER_URL: string;
	RATELIMIT_SERVER_KEY: string;
	ALLOWED_ORIGIN: string;
	GENERIC_REQ_PER_DAY: number;
}
