#:schema node_modules/wrangler/config-schema.json
name = "s2n-demo-cf-gateway"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://speech2diet.pages.dev,https://fitvoice.dgop92.me"
GENERIC_REQ_PER_DAY = 6

[triggers]
crons = ["0 1 * * *"]