/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AudioMetadataCreateInput {
  data: {
    mimeType: 'audio/mp3' | 'audio/mpeg';
  };
}
