/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface FoodReportReviewSearchInput {
  searchBy: {
    id: string;
    mealReviewReportId: string;
  };
}
