/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface FoodCreateInput {
  calories: number;
  carbohydrates: number;
  description: string[];
  fat: number;
  foodName: string;
  foodSource: 'user_db' | 'system_db';
  id: string;
  otherNames: string[];
  portionReference: number;
  portionUnit: string;
  protein: number;
}
