/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { FoodItemCreateInput } from '.';

export interface FoodReportReviewCreateInput {
  systemResult: {
    foundFoodItem: FoodItemCreateInput | null;
    suggestions: FoodItemCreateInput[];
  };
  userReport: {
    amount: number;
    description: string[];
    foodName: string;
    unit: string;
  };
}

export interface FoodReportReviewSearchInput {
  searchBy: {
    id: string;
    mealReviewReportId: string;
  };
}
