/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { FoodReportReviewCreateInput } from '.';

export interface MealReportReviewCreateInput {
  data: {
    audioId: string;
    dbLookupPreference: 'user_db-system_db' | 'system_db-user_db' | 'user-db' | 'system-db';
    foodReports: FoodReportReviewCreateInput[];
    mealRecordedAt: Date;
    rawTranscript: string;
    userId: string;
  };
}

export interface MealReportReviewOptions {
  fetchFoodReports?: boolean;
}

export interface MealReportReviewPagination {
  /**
   * Limit results per request
   */
  limit?: number;
}

export interface MealReportReviewSearchInput {
  options?: MealReportReviewOptions;
  pagination?: MealReportReviewPagination;
  searchBy?: {
    id?: string;
    pending?: boolean;
  };
  sortBy?: {
    createdAt?: 'asc' | 'desc';
  };
}

export interface MealReportReviewUpdateInput {
  data: {
    pending: boolean;
  };
  searchBy: {
    id: string;
  };
}
