/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface MealReportReviewOptions {
  fetchFoodReports?: boolean;
}

export interface MealReportReviewPagination {
  /**
   * Limit results per request
   */
  limit?: number;
}

export interface MealReportReviewSearchInput {
  options?: MealReportReviewOptions;
  pagination?: MealReportReviewPagination;
  searchBy?: {
    id?: string;
    pending?: boolean;
  };
  sortBy?: {
    createdAt?: 'asc' | 'desc';
  };
}

export interface MealReportReviewUpdateInput {
  data: {
    pending: boolean;
  };
  searchBy: {
    id: string;
  };
}
