/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface NutritionalInfoMRRBetweenDateInput {
  mealRecordedEnd: Date;
  mealRecordedStart: Date;
}
