@startuml high-level-component-diagram
skinparam padding 10
skinparam defaultTextAlignment center

!includesub components/external-services.puml!AUTH_SERVICE
!includesub components/external-services.puml!CORE_DB
!includesub components/external-services.puml!AUDIO_STORAGE

!includesub components/main-components.puml!MOBILE_APPLICATION
!includesub components/main-components.puml!SPEECH_2_DIET_API
!includesub components/main-components.puml!MRR_UPLOAD
!includesub components/main-components.puml!MESSAGE_QUEUE
!includesub components/main-components.puml!SPEECH_2_NUTRITION
!includesub components/main-components.puml!NUTRITION_DB

!includesub components/external-services.puml!LLM_SERVICE
!includesub components/external-services.puml!SPEECH_2_TEXT


Speech2DietAPI --> CoreDB : manages app data \n [http]
Speech2DietAPI --> AudioStorage : saves audio files \n [http]
Speech2DietAPI -- MessageQueue

Speech2Nutrition --> NutritionDB : queries nutrition information
Speech2Nutrition --> LLMService : parses text using
Speech2Nutrition --> Speech2TextService : transcribes audios using
Speech2Nutrition -u- MessageQueue
MRRUpload -l- MessageQueue
Speech2Nutrition --> AudioStorage : reads audio files \n [http]

MobileApplication --> Speech2DietAPI : makes requests to \n [http]
MobileApplication --> AuthService : authenticates users \n [http]

@enduml