/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { FoodCreateInput } from '.';

export interface FoodItemCreateInput {
  amount: number;
  food: FoodCreateInput;
  score: number;
  servingSizeWasUsed: boolean;
  unitTransformationInfo: UnitTransformationInfo | null;
  unitWasTransformed: boolean;
}

export interface UnitTransformationInfo {
  finalUnit: string;
  originalUnit: string;
  transformationFactor: number;
}
