/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { FoodReportReviewCreateInput } from '.';

export interface MealReportReviewCreateInput {
  data: {
    appUserId: string;
    audioId: string;
    dbLookupPreference: 'user_db-system_db' | 'system_db-user_db' | 'user-db' | 'system-db';
    foodReports: FoodReportReviewCreateInput[];
    mealRecordedAt: Date;
    rawTranscript: string;
  };
}
