@baseUrl = http://localhost:8080/api/v1/test-util
@contentType = application/json


### Clear the users in firebase auth and delete all collections in firestore
### So far it only clears the users in the firestore
POST {{baseUrl}}/clear-all HTTP/1.1
content-type: {{contentType}}


### Create dummy users in firebase auth and firestore
POST {{baseUrl}}/setup-data HTTP/1.1
content-type: {{contentType}}

{
    "moduleToSetup": "auth"
}

### Setup meal report review and food report review data
POST {{baseUrl}}/setup-data HTTP/1.1
content-type: {{contentType}}

{
    "moduleToSetup": "foodlog",
    "appUserIds": ["GvTNYsqJ6EsvXq9TNLkBH2r603eb", "Xl7XEJAi64iH09Z0SHwavXdYOwCu"]
}
