import { NutritionInformationResponse } from "./nutrition-information-response";

export const NUTRITION_INFORMATION_RESPONSE_EXAMPLE: NutritionInformationResponse =
  {
    raw_transcript:
      "hoy almorcé una taza de arroz blanco con dos huevos medianos y 80 gramos de carne de res",
    food_responses: [
      {
        food_record: {
          food: {
            id: "usdaFoundation/e58f3c19-9bcb-4704-b937-7950caadd1c6",
            food_name: "arroz",
            other_names: [],
            description: ["blanco", "grano largo", "sin enriquecer", "crudo"],
            full_description: [
              "arroz",
              "blanco",
              "grano",
              "enriquecer",
              "crudo",
            ],
            portion_size: 100.0,
            portion_size_unit: "g",
            serving_size: 75.0,
            serving_size_unit: "g",
            food_source: "system_db",
            calories: 359.0,
            protein: 7.04,
            fat: 1.03,
            carbohydrates: 80.3,
          },
          score: 4.0,
          amount: 200.0,
          unit_was_transformed: true,
          serving_size_was_used: false,
          unit_transformation_info: {
            original_unit: "taza",
            final_unit: "g",
            transformation_factor: 200.0,
          },
        },
        suggestions: [
          {
            food: {
              id: "bedca/1f599662-b8ec-4300-b165-092a7e7e01c8",
              food_name: "Arroz",
              other_names: [],
              description: [],
              full_description: ["arroz"],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 100.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 385.0,
              protein: 7.0,
              fat: 0.9,
              carbohydrates: 86.0,
            },
            score: 2.0,
            amount: 200.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "taza",
              final_unit: "g",
              transformation_factor: 200.0,
            },
          },
          {
            food: {
              id: "usdaFoundation/3af8bcef-a3a0-4a7b-ba95-15415f685527",
              food_name: "arroz",
              other_names: [],
              description: [
                "integral",
                "grano largo",
                "sin enriquecer",
                "crudo",
              ],
              full_description: [
                "arroz",
                "integral",
                "grano",
                "enriquecer",
                "crudo",
              ],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 75.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 366.0,
              protein: 7.25,
              fat: 3.31,
              carbohydrates: 76.7,
            },
            score: 2.0,
            amount: 200.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "taza",
              final_unit: "g",
              transformation_factor: 200.0,
            },
          },
          {
            food: {
              id: "bedca/2750f2c3-47ea-4719-97ed-e10157e0772a",
              food_name: "Arroz",
              other_names: [],
              description: ["hervido"],
              full_description: ["arroz", "hervido"],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 100.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 129.0,
              protein: 2.66,
              fat: 0.28,
              carbohydrates: 27.9,
            },
            score: 2.0,
            amount: 200.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "taza",
              final_unit: "g",
              transformation_factor: 200.0,
            },
          },
        ],
        user_amount: 1.0,
        user_unit: "taza",
      },
      {
        food_record: {
          food: {
            id: "usdaFoundation/b408516e-d572-45b5-901d-d12803279b7a",
            food_name: "huevos",
            other_names: [],
            description: ["grado a", "grande", "clara de huevo"],
            full_description: ["huevos", "grado", "", "clara huevo"],
            portion_size: 100.0,
            portion_size_unit: "g",
            serving_size: 50.0,
            serving_size_unit: "g",
            food_source: "system_db",
            calories: 52.0,
            protein: 10.7,
            fat: 0.0,
            carbohydrates: 2.36,
          },
          score: 2.0,
          amount: 100.0,
          unit_was_transformed: true,
          serving_size_was_used: false,
          unit_transformation_info: {
            original_unit: "",
            final_unit: "g",
            transformation_factor: 50.0,
          },
        },
        suggestions: [
          {
            food: {
              id: "usdaFoundation/bcdea0ba-c26b-4869-bf47-7250871735a8",
              food_name: "huevos",
              other_names: [],
              description: ["categoría a", "grande", "huevo entero"],
              full_description: ["huevos", "categoria", "", "huevo entero"],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 50.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 143.0,
              protein: 12.4,
              fat: 9.96,
              carbohydrates: 0.96,
            },
            score: 2.0,
            amount: 100.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "",
              final_unit: "g",
              transformation_factor: 50.0,
            },
          },
          {
            food: {
              id: "usdaFoundation/724d2fb8-bd93-4ef9-8684-922f3478f6c2",
              food_name: "huevos",
              other_names: [],
              description: ["categoría a", "grande", "yema de huevo"],
              full_description: ["huevos", "categoria", "", "yema huevo"],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 50.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 328.0,
              protein: 16.2,
              fat: 28.8,
              carbohydrates: 1.02,
            },
            score: 2.0,
            amount: 100.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "",
              final_unit: "g",
              transformation_factor: 50.0,
            },
          },
          {
            food: {
              id: "usdaFoundation/bce9ad36-606e-4116-bb09-bc87c1ac5ae1",
              food_name: "huevo",
              other_names: [],
              description: ["yema", "crudo", "congelado", "pasteurizado"],
              full_description: [
                "huevo",
                "yema",
                "crudo",
                "congelado",
                "pasteurizado",
              ],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 50.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 291.0,
              protein: 15.6,
              fat: 25.1,
              carbohydrates: 0.59,
            },
            score: 1.0,
            amount: 100.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "",
              final_unit: "g",
              transformation_factor: 50.0,
            },
          },
        ],
        user_amount: 2.0,
        user_unit: "",
      },
      {
        food_record: {
          food: {
            id: "usdaFoundation/94fe65c1-54e5-447b-95cb-2ab0a9ecf2f3",
            food_name: "carne de vacuno",
            other_names: ["carne de res"],
            description: ["molida", "80% carne magra / 20% grasa", "crudo"],
            full_description: [
              "carne vacuno",
              "carne res",
              "molida",
              "80% carne magra 20% grasa",
              "crudo",
            ],
            portion_size: 100.0,
            portion_size_unit: "g",
            serving_size: 85.0,
            serving_size_unit: "g",
            food_source: "system_db",
            calories: 243.0,
            protein: 17.5,
            fat: 19.4,
            carbohydrates: 0.0,
          },
          score: 4.0,
          amount: 80.0,
          unit_was_transformed: true,
          serving_size_was_used: false,
          unit_transformation_info: {
            original_unit: "gramos",
            final_unit: "g",
            transformation_factor: 1.0,
          },
        },
        suggestions: [
          {
            food: {
              id: "usdaFoundation/bbff9514-986a-48de-a247-c6a172564251",
              food_name: "carne de vacuno",
              other_names: ["carne de res"],
              description: ["molida", "90% carne magra / 10% grasa", "crudo"],
              full_description: [
                "carne vacuno",
                "carne res",
                "molida",
                "90% carne magra 10% grasa",
                "crudo",
              ],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 85.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 185.0,
              protein: 18.2,
              fat: 12.8,
              carbohydrates: 0.0,
            },
            score: 4.0,
            amount: 80.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "gramos",
              final_unit: "g",
              transformation_factor: 1.0,
            },
          },
          {
            food: {
              id: "usdaFoundation/6b21edf4-d49d-46ea-9905-4156f45c1756",
              food_name: "carne de vacuno",
              other_names: ["carne de res", "carne de vaca"],
              description: [
                "redondo",
                "asado",
                "deshuesado",
                "sólo magro separable",
                "recortado a 0 de grasa",
                "selecto",
                "crudo",
              ],
              full_description: [
                "carne vacuno",
                "carne res",
                "carne vaca",
                "redondo",
                "asado",
                "deshuesado",
                "magro separable",
                "recortado 0 grasa",
                "selecto",
                "crudo",
              ],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 85.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 116.0,
              protein: 23.7,
              fat: 2.41,
              carbohydrates: 0.0,
            },
            score: 4.0,
            amount: 80.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "gramos",
              final_unit: "g",
              transformation_factor: 1.0,
            },
          },
          {
            food: {
              id: "usdaFoundation/fac8fb20-4d43-45d0-a5be-c86e5f1cc1f5",
              food_name: "carne de vaca",
              other_names: ["carne de res"],
              description: [
                "lomo",
                "asado de lomo",
                "sólo magro separable",
                "deshuesado",
                "recortado a 0 grasa",
                "selecto",
                "cocido",
                "asado",
              ],
              full_description: [
                "carne vaca",
                "carne res",
                "lomo",
                "asado lomo",
                "magro separable",
                "deshuesado",
                "recortado 0 grasa",
                "selecto",
                "cocido",
                "asado",
              ],
              portion_size: 100.0,
              portion_size_unit: "g",
              serving_size: 85.0,
              serving_size_unit: "g",
              food_source: "system_db",
              calories: 168.0,
              protein: 27.7,
              fat: 6.36,
              carbohydrates: 0.0,
            },
            score: 4.0,
            amount: 80.0,
            unit_was_transformed: true,
            serving_size_was_used: false,
            unit_transformation_info: {
              original_unit: "gramos",
              final_unit: "g",
              transformation_factor: 1.0,
            },
          },
        ],
        user_amount: 80.0,
        user_unit: "gramos",
      },
    ],
    food_requests: [
      {
        food_name: "arroz blanco",
        description: [],
        amount: 1.0,
        unit: "taza",
      },
      {
        food_name: "huevos",
        description: ["medianos"],
        amount: 2.0,
        unit: "",
      },
      {
        food_name: "carne de res",
        description: [],
        amount: 80.0,
        unit: "gramos",
      },
    ],
    ni_request: {
      user_id: "adskju123",
      audio_id: "audio123",
      db_lookup_preference: "system_db",
      meal_recorded_at: "2024-06-18T20:00:35.046786",
    },
  };
