@startuml foodlog-activity-diagram
skinparam padding 2

|User|
start
:record meal by\nvoice;

|Speech2Diet-API|
:save audio to audio storage;
:send request\nto queue;

|Speech2Nutrition|
:get nutritional information;
:send response\nto queue;

|MRR-Upload|
:send request\nto s2d-api;

|Speech2Diet-API|
:save results in\nuser's meal report\nreviews db;

repeat
  |User|
  :review and modify results;
repeat while (Results are good?) is (no)
->yes;
|Speech2Diet-API|
:save foods in user's food log;
stop

@enduml