@startuml external-services-definitions

!startsub FIREBASE_AUTH
node "<<external-service>> \nFirebase Auth" as FirebaseAuth
!endsub

!startsub FIRESTORE_DB
database "<<external-service>> \nFirestore DB" as FirestoreDB
!endsub

!startsub AUDIO_STORAGE
node "<<external-service>> \nAudio Storage" as AudioStorage
!endsub

!startsub CHAT_GPT
node "<<external-service>> \nChat GPT" as ChatGPT
!endsub

!startsub WHISPER
node "<<external-service>> \nWhisper" as Whisper
!endsub

@enduml