@startuml external-services-definitions

!startsub AUTH_SERVICE
node "<<external-service>> \nAuth Service" as AuthService
!endsub

!startsub CORE_DB
database "<<external-service>> \nCore DB" as CoreDB
!endsub

!startsub AUDIO_STORAGE
node "<<external-service>> \nAudio Storage" as AudioStorage
!endsub

!startsub LLM_SERVICE
node "<<external-service>> \nLLM" as LLMService
!endsub

!startsub SPEECH_2_TEXT
node "<<external-service>> \nSpeechToText Service" as Speech2TextService
!endsub

@enduml