name: Speech 2 Diet API CD Workflow

on:
  push:
    branches: [s2d-api]
    paths:
      - "s2d-api/src/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./s2d-api

jobs:    
  ci:
    uses: ./.github/workflows/s2d-api-ci-workflow.yml
    secrets:
      FIREBASE_TEST_API_KEY: ${{ secrets.FIREBASE_TEST_API_KEY }}
      FIREBASE_TEST_CREDENTIALS_CONTENT: ${{ secrets.FIREBASE_TEST_CREDENTIALS_CONTENT }}
  generate-api-docs:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm ci

      - name: Generate api docs
        run: npm run api-docs
        env:
          NODE_ENV: test
          SECRETS_FROM: env
          APP_PORT: 8080
          AWS_REGION: us-east-1
          LOG_LEVEL: info
          MRR_UPLOAD_API_KEY: dummy
          # as I only using this environment to generate the API specification. 
          # I can safely use the test credentials because no call to the firebase will be made.
          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.FIREBASE_TEST_CREDENTIALS_CONTENT }}
      
      # Upload the generated api docs
      # Probably, we should look for a storage solution for this file
      - name: Upload api docs
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: ./s2d-api/s2d-api-swagger-spec.json
          if-no-files-found: error
          retention-days: 10
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Dummy deploy
        run: echo "Deploying to production"
        env:
          NODE_ENV: prod

