name: Speech2Nutrition CI Workflow

on:
  pull_request:
    branches: [speech2nutrition]
    paths:
      - "speech2nutrition/**"
      - "!speech2nutrition/README.md"
      - "!speech2nutrition/docs/**"
      - "!speech2nutrition/env_examples/**"
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:


defaults:
  run:
    working-directory: ./speech2nutrition

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment with python and poetry
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.10"
          poetry-version: "1.8.3"
          working-directory: ./speech2nutrition
      
      - name: Check poetry lock
        run: poetry check --lock

      - name: Run ruff check
        run: poetry run ruff check

      - name: Run ruff format
        run: poetry run ruff format
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment with python and poetry
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.10"
          poetry-version: "1.8.3"
          working-directory: ./speech2nutrition

      - name: Run tests
        run: |
          poetry run pytest -v --junitxml=pytest-junit-report.xml
        env:
          SERVICE_ENVIRONMENT: test
          SECRETS_FROM: env
          LOGGING_CONFIG_FILE: logging-dev.conf
          MOCK_SERVICES: True

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: pytest-junit-report.xml
          if-no-files-found: error
          retention-days: 1
